spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3307/servicebox
    username: sbuser
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.wp.pl
    port: 465
    username: servicebox-liveoak@wp.pl
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

mail:
  from: servicebox-liveoak@wp.pl

app:
  createSampleDatabase: false

